'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------
Namespace T114462

    Public Partial Class [Default]

        ''' <summary>
        ''' form1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected form1 As Global.System.Web.UI.HtmlControls.HtmlForm

        ''' <summary>
        ''' Grid control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected Grid As Global.DevExpress.Web.ASPxGridView

        ''' <summary>
        ''' deleteButton control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected deleteButton As Global.DevExpress.Web.GridViewCommandColumnCustomButton
    End Class
End Namespace
